### ISSUE TITLE
[Request] Only enable SwipeUpLockX at the 1st page of App

### ISSUE THREAD

**Issue by snowleopardw** [akaspektro/SwipeUpLockX#1]
Is it possible to include a version where by swiping up to lock only works on the home page? 
Therefore when in other pages (page 2,3 etc) we can still return to the home page (1st page of the home screen by swiping up). Instead of just locking the device. 

Excuse my poor English. 
Thank you! 

Original post: https://www.reddit.com/r/jailbreak/comments/7tirhz/release_swipeuplockx_for_iphone_x/dtcvppi/?context=3

**Comment by goodboydheeraj** [comment]
Can you add option to disable locking device when home button is pressed? Happens on devices with home button!

**Comment by akaspektro** [comment]
That´s why i stated it is only for iPhone X. Will work on those requests when possible, as well as a preference bundle to let you guys decide if the swipe will lock on any SB page/open folder or only in the main page.

**Comment by RaxisX** [comment]
To expand upon this, would it be possible to also disable the ‘Swipe up to Lock’ motion when you’re within the edit mode (jiggling icons, to delete/move icons), as I generally use the swipe up motion to exit that mode. Thanks!

**Comment by goodboydheeraj** [comment]
Thanks. I'll be looking forward the update!
I got one more request. Can you add option or just disable swipetolock when in notification center and in the notification center widget?
